// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	v1 "github.com/kaisawind/mongodb-proxy/v1"

	strfmt "github.com/go-openapi/strfmt"
)

// AnnotationQueryReader is a Reader for the AnnotationQuery structure.
type AnnotationQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AnnotationQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAnnotationQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAnnotationQueryOK creates a AnnotationQueryOK with default headers values
func NewAnnotationQueryOK() *AnnotationQueryOK {
	return &AnnotationQueryOK{}
}

/*AnnotationQueryOK handles this case with default header values.

get annotations successfully.
*/
type AnnotationQueryOK struct {
	Payload *v1.Annotations
}

func (o *AnnotationQueryOK) Error() string {
	return fmt.Sprintf("[POST /annotations][%d] annotationQueryOK  %+v", 200, o.Payload)
}

func (o *AnnotationQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(v1.Annotations)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
