// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	v1 "github.com/kaisawind/mongodb-proxy/v1"
)

// NewMetricFindQueryParams creates a new MetricFindQueryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMetricFindQueryParams() *MetricFindQueryParams {
	return &MetricFindQueryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMetricFindQueryParamsWithTimeout creates a new MetricFindQueryParams object
// with the ability to set a timeout on a request.
func NewMetricFindQueryParamsWithTimeout(timeout time.Duration) *MetricFindQueryParams {
	return &MetricFindQueryParams{
		timeout: timeout,
	}
}

// NewMetricFindQueryParamsWithContext creates a new MetricFindQueryParams object
// with the ability to set a context for a request.
func NewMetricFindQueryParamsWithContext(ctx context.Context) *MetricFindQueryParams {
	return &MetricFindQueryParams{
		Context: ctx,
	}
}

// NewMetricFindQueryParamsWithHTTPClient creates a new MetricFindQueryParams object
// with the ability to set a custom HTTPClient for a request.
func NewMetricFindQueryParamsWithHTTPClient(client *http.Client) *MetricFindQueryParams {
	return &MetricFindQueryParams{
		HTTPClient: client,
	}
}

/* MetricFindQueryParams contains all the parameters to send to the API endpoint
   for the metric find query operation.

   Typically these are written to a http.Request.
*/
type MetricFindQueryParams struct {

	/* Options.

	   The options to query.
	*/
	Options *v1.Target

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the metric find query params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MetricFindQueryParams) WithDefaults() *MetricFindQueryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the metric find query params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MetricFindQueryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the metric find query params
func (o *MetricFindQueryParams) WithTimeout(timeout time.Duration) *MetricFindQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the metric find query params
func (o *MetricFindQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the metric find query params
func (o *MetricFindQueryParams) WithContext(ctx context.Context) *MetricFindQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the metric find query params
func (o *MetricFindQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the metric find query params
func (o *MetricFindQueryParams) WithHTTPClient(client *http.Client) *MetricFindQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the metric find query params
func (o *MetricFindQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOptions adds the options to the metric find query params
func (o *MetricFindQueryParams) WithOptions(options *v1.Target) *MetricFindQueryParams {
	o.SetOptions(options)
	return o
}

// SetOptions adds the options to the metric find query params
func (o *MetricFindQueryParams) SetOptions(options *v1.Target) {
	o.Options = options
}

// WriteToRequest writes these params to a swagger request
func (o *MetricFindQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Options != nil {
		if err := r.SetBodyParam(o.Options); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
