// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MetricFindQueryReader is a Reader for the MetricFindQuery structure.
type MetricFindQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MetricFindQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMetricFindQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMetricFindQueryOK creates a MetricFindQueryOK with default headers values
func NewMetricFindQueryOK() *MetricFindQueryOK {
	return &MetricFindQueryOK{}
}

/* MetricFindQueryOK describes a response with status code 200, with default header values.

find metric options successfully.
*/
type MetricFindQueryOK struct {
	Payload interface{}
}

func (o *MetricFindQueryOK) Error() string {
	return fmt.Sprintf("[POST /search][%d] metricFindQueryOK  %+v", 200, o.Payload)
}
func (o *MetricFindQueryOK) GetPayload() interface{} {
	return o.Payload
}

func (o *MetricFindQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
