// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TestDatasourceReader is a Reader for the TestDatasource structure.
type TestDatasourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TestDatasourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTestDatasourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTestDatasourceOK creates a TestDatasourceOK with default headers values
func NewTestDatasourceOK() *TestDatasourceOK {
	return &TestDatasourceOK{}
}

/* TestDatasourceOK describes a response with status code 200, with default header values.

connection successfully.
*/
type TestDatasourceOK struct {
}

func (o *TestDatasourceOK) Error() string {
	return fmt.Sprintf("[GET /][%d] testDatasourceOK ", 200)
}

func (o *TestDatasourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
