// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTestDatasourceParams creates a new TestDatasourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTestDatasourceParams() *TestDatasourceParams {
	return &TestDatasourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTestDatasourceParamsWithTimeout creates a new TestDatasourceParams object
// with the ability to set a timeout on a request.
func NewTestDatasourceParamsWithTimeout(timeout time.Duration) *TestDatasourceParams {
	return &TestDatasourceParams{
		timeout: timeout,
	}
}

// NewTestDatasourceParamsWithContext creates a new TestDatasourceParams object
// with the ability to set a context for a request.
func NewTestDatasourceParamsWithContext(ctx context.Context) *TestDatasourceParams {
	return &TestDatasourceParams{
		Context: ctx,
	}
}

// NewTestDatasourceParamsWithHTTPClient creates a new TestDatasourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewTestDatasourceParamsWithHTTPClient(client *http.Client) *TestDatasourceParams {
	return &TestDatasourceParams{
		HTTPClient: client,
	}
}

/* TestDatasourceParams contains all the parameters to send to the API endpoint
   for the test datasource operation.

   Typically these are written to a http.Request.
*/
type TestDatasourceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the test datasource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TestDatasourceParams) WithDefaults() *TestDatasourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the test datasource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TestDatasourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the test datasource params
func (o *TestDatasourceParams) WithTimeout(timeout time.Duration) *TestDatasourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the test datasource params
func (o *TestDatasourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the test datasource params
func (o *TestDatasourceParams) WithContext(ctx context.Context) *TestDatasourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the test datasource params
func (o *TestDatasourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the test datasource params
func (o *TestDatasourceParams) WithHTTPClient(client *http.Client) *TestDatasourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the test datasource params
func (o *TestDatasourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *TestDatasourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
