// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Annotations encodes the information provided by Grafana in its requests.
// swagger:model Annotations
type Annotations struct {

	// annotation
	Annotation *Annotation `json:"annotation,omitempty"`

	// range
	Range *Range `json:"range,omitempty"`
}

// Validate validates this annotations
func (m *Annotations) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnnotation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRange(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Annotations) validateAnnotation(formats strfmt.Registry) error {

	if swag.IsZero(m.Annotation) { // not required
		return nil
	}

	if m.Annotation != nil {
		if err := m.Annotation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("annotation")
			}
			return err
		}
	}

	return nil
}

func (m *Annotations) validateRange(formats strfmt.Registry) error {

	if swag.IsZero(m.Range) { // not required
		return nil
	}

	if m.Range != nil {
		if err := m.Range.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("range")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Annotations) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Annotations) UnmarshalBinary(b []byte) error {
	var res Annotations
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
