// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Target data target.
//
// swagger:model Target
type Target struct {

	// ref Id
	RefID string `json:"refId,omitempty"`

	// target
	Target string `json:"target,omitempty"`

	// type
	// Enum: [timeserie table]
	Type *string `json:"type,omitempty"`
}

// Validate validates this target
func (m *Target) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var targetTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["timeserie","table"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		targetTypeTypePropEnum = append(targetTypeTypePropEnum, v)
	}
}

const (

	// TargetTypeTimeserie captures enum value "timeserie"
	TargetTypeTimeserie string = "timeserie"

	// TargetTypeTable captures enum value "table"
	TargetTypeTable string = "table"
)

// prop value enum
func (m *Target) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, targetTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Target) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this target based on context it is used
func (m *Target) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Target) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Target) UnmarshalBinary(b []byte) error {
	var res Target
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
