// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Timeserie timeserie
//
// swagger:model Timeserie
type Timeserie struct {

	// datapoints
	Datapoints [][]interface{} `json:"datapoints"`

	// target
	Target string `json:"target,omitempty"`
}

// Validate validates this timeserie
func (m *Timeserie) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this timeserie based on context it is used
func (m *Timeserie) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Timeserie) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Timeserie) UnmarshalBinary(b []byte) error {
	var res Timeserie
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
