// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger of MongoDB for Grafana plugin
//
//  This is a sample mongodb proxy server.
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 1.0.0
//  License: MIT License https://mit-license.org/
//  Contact: <wind.kaisa@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
