// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/kaisawind/mongodb-proxy/v1"
)

// AnnotationQueryOKCode is the HTTP code returned for type AnnotationQueryOK
const AnnotationQueryOKCode int = 200

/*AnnotationQueryOK get annotations successfully.

swagger:response annotationQueryOK
*/
type AnnotationQueryOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Annotations `json:"body,omitempty"`
}

// NewAnnotationQueryOK creates AnnotationQueryOK with default headers values
func NewAnnotationQueryOK() *AnnotationQueryOK {

	return &AnnotationQueryOK{}
}

// WithPayload adds the payload to the annotation query o k response
func (o *AnnotationQueryOK) WithPayload(payload *v1.Annotations) *AnnotationQueryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the annotation query o k response
func (o *AnnotationQueryOK) SetPayload(payload *v1.Annotations) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AnnotationQueryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
