// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// MetricFindQueryOKCode is the HTTP code returned for type MetricFindQueryOK
const MetricFindQueryOKCode int = 200

/*MetricFindQueryOK find metric options successfully.

swagger:response metricFindQueryOK
*/
type MetricFindQueryOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewMetricFindQueryOK creates MetricFindQueryOK with default headers values
func NewMetricFindQueryOK() *MetricFindQueryOK {

	return &MetricFindQueryOK{}
}

// WithPayload adds the payload to the metric find query o k response
func (o *MetricFindQueryOK) WithPayload(payload interface{}) *MetricFindQueryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the metric find query o k response
func (o *MetricFindQueryOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MetricFindQueryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
