// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/kaisawind/mongodb-proxy/v1"
)

// QueryOKCode is the HTTP code returned for type QueryOK
const QueryOKCode int = 200

/*QueryOK query data successfully.

swagger:response queryOK
*/
type QueryOK struct {

	/*
	  In: Body
	*/
	Payload v1.Timeseries `json:"body,omitempty"`
}

// NewQueryOK creates QueryOK with default headers values
func NewQueryOK() *QueryOK {

	return &QueryOK{}
}

// WithPayload adds the payload to the query o k response
func (o *QueryOK) WithPayload(payload v1.Timeseries) *QueryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the query o k response
func (o *QueryOK) SetPayload(payload v1.Timeseries) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *QueryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = v1.Timeseries{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
