// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/kaisawind/mongodb-proxy/v1"
)

// NewQueryParams creates a new QueryParams object
// no default values defined in spec.
func NewQueryParams() QueryParams {

	return QueryParams{}
}

// QueryParams contains all the bound params for the query operation
// typically these are obtained from a http.Request
//
// swagger:parameters Query
type QueryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The options to query.
	  In: body
	*/
	Options *v1.Query
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewQueryParams() beforehand.
func (o *QueryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body v1.Query
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("options", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Options = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
