// Code generated by go-swagger; DO NOT EDIT.

package simple_json

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TestDatasourceOKCode is the HTTP code returned for type TestDatasourceOK
const TestDatasourceOKCode int = 200

/*TestDatasourceOK connection successfully.

swagger:response testDatasourceOK
*/
type TestDatasourceOK struct {
}

// NewTestDatasourceOK creates TestDatasourceOK with default headers values
func NewTestDatasourceOK() *TestDatasourceOK {

	return &TestDatasourceOK{}
}

// WriteResponse to the client
func (o *TestDatasourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
